### ISSUE TITLE
Error Upgrading from 3.4.10 to 3.5.1 (Missing Keys)

### ISSUE THREAD

**Issue by alecbcs** [standardnotes/desktop#625]
After updating to 3.5.1 today on the Linux App Image, I'm unable to view any notes. I'm seeing a "Missing keys" error on the note panels? Signing out and back in makes no difference.

![image](https://user-images.githubusercontent.com/19558067/97909384-59965b00-1d05-11eb-876d-45117e073679.png)

**Comment by mobitar** [comment]
Can you first click Help > Toggle Error Console, then ensure the Console tab is selected, then take a screenshot of what you see?

Then, if your data is properly synced to your account, please sign out then sign back in. This should resolve the issue, which appears to be a failed local migration.

**Comment by alecbcs** [comment]
Here's a screenshot of the console log.
![image](https://user-images.githubusercontent.com/19558067/97924026-3f1bac00-1d1c-11eb-9db2-1bea190e9a88.png)

Logging out, as well as clearing the ~/.config/StandardNotes/ directory and signing in to a new install still results in the same issue. I still have access to all the files on another machine running 3.4.10 so it doesn't look like it's effecting the synced data.

**Comment by mobitar** [comment]
Thanks for the info. Can you please email me with your account email so I can investigate this further? Email in GH bio.

**Comment by alecbcs** [comment]
@mobitar just checking in, I sent you the info as requested but I haven't heard anything back yet. Any updates on this bug?

**Comment by mobitar** [comment]
@alecbcs sorry for the delay. Your account looks fine, so it must be something with the local software. Can you test any of our recent releases to see if they've fixed the issue? We've had many releases in the past few days. The latest desktop version is 3.5.6. Please try signing out and back in with this version.

**Comment by alecbcs** [comment]
@mobitar absolutely no worries! I'm still getting the same "missing keys" error on both Mac and Linux 3.5.6 after fulling logging out wiping local data and logging back in. I experimented logging in with the account I had previously been using with another email address and that one successfully logs in with no issues. So I wonder if this has anything to do with exporting and importing notes from another account?

**Comment by baptiste-grob** [comment]
Hey @alecbcs, could you elaborate on the _exporting and importing notes from another account_ bit? Did you import data from your older account into this one?
If you could try signing in from https://app.standardnotes.org so we can confirm this is an account issue and not a local software issue that would be great.

**Comment by alecbcs** [comment]
@baptiste-grob I can confirm that I'm experiencing the same broken state on the web app as with the desktop app.

> could you elaborate on the exporting and importing notes from another account bit? Did you import data from your older account into this one?

Absolutely, as part of the process from moving from one primary email to another, I changed the email for my standard notes extended account and created a new standard notes sync account as described in [this tutorial](https://standardnotes.org/help/7/how-can-i-change-my-account-email). I exported all of my previous notes from my previous standard notes sync account, logged out and cleared the local data, and then logged into my new sync account and imported my backup from the old account. After logging back into my extended account I enabled the extensions & themes I'd been using on my old account and then proceeded to log out of my old account on all of my devices and into the new one, which synced all of the notes, extensions, etc... successfully to my devices. After upgrading to 3.5.1 (or later) on each of these devices I'm running into the same error with "keys missing". As part of testing is bug I noticed that going back to my old sync account that account correctly launches under versions >= 3.5.1. So it must be some part of exporting/importing the data that is causing issues in the new version correct?

**Comment by baptiste-grob** [comment]
Thank you so much for your detailed response. This must indeed be related to your import. Do you remember when approximately you transferred your data to your new account, so we can look into the exporting functionality of the most recently released app version at the time?

**Comment by baptiste-grob** [comment]
Also, did you use an encrypted or a decrypted backup?

**Comment by alecbcs** [comment]
> Thank you so much for your detailed response. This must indeed be related to your import. Do you remember when approximately you transferred your data to your new account, so we can look into the exporting functionality of the most recently released app version at the time?

@baptiste-grob I've still got the exported backup, checking the metadata I went through this transferring process on `Fri 30 Oct 2020`. I believe it was an unencrypted backup although looking at the file it looks either encrypted or encoded, I was following the tutorial mentioned before to manually create the export in the account tab.

**Comment by baptiste-grob** [comment]
Thank you again. We haven't been able to reproduce your issue yet so if you want to start using the v3.5 app you could export a backup from version 3.4.10, reset your account, and then re-import your data, like so:

1. Ensure 3.5 apps can decrypt your latest data
    1. From your 3.4.10 app, export a decrypted backup.
    2. Create a third (temporary) account on a 3.5 app and import your backup there.
    3. Ensure all your notes and tags are there and wait for syncing to complete (You can check syncing status in the _Account_ menu).
    4. Sign out, then back in.

If you can successfully see all your notes and tags, you can start resetting your main account (the one you originally imported  your data to):

2. Go to https://standardnotes.org/reset
3. Enter your main account's email address
4. After your account has been deleted, register in a 3.5 app.
5. Import you backup file into the app.
6. Ensure all your notes and tags are there and wait for syncing to complete.
7. After a couple days of usage, if everything works as expected, use https://standardnotes.org/reset again to delete your third temporary account.

This is pretty involved, but if you follow these steps you are guaranteed not to lose any data. While I would like to tell you that we will figure out your issue in a respectable time frame

**Comment by alecbcs** [comment]
@baptiste-grob no worries, thank you for the in depth information. It's curious you all haven't been able to reproduce getting into this failed state. Leads me to believe that I probably did something wrong in the migration process or something happened with the timing of the update and my Linux App Syncing. Thank you all @mobitar & @baptiste-grob for your help tracking down this issue, I really appreciate all your help. I'll go ahead and close this issue.

**Comment by baptiste-grob** [comment]
Hey @alecbcs, we've just published version 3.5.11 which includes a fix for a situation that could potentially be related to yours: https://github.com/standardnotes/desktop/releases/tag/v3.5.11
